language: node_js
node_js:
  - 'stable'
before_install:
  - cd exam
  - cd weather
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: exam/weather/build
  on:
    branch:
      - master
      - devel
      - exam
